### ISSUE TITLE
stack.startsWith is not a function

### ISSUE THREAD

**Issue by Zjcompt** [Meteor-Community-Packages/meteor-elastic-apm#49]
I am running into an issue where my Meteor methods are not returning errors. It appears that the agent is recording the server side error but before the error is sent to the client this happens:

```
W20200626-22:41:49.476(-4)? (STDERR) (node:54484) UnhandledPromiseRejectionWarning: TypeError: stack.startsWith is not a function
W20200626-22:41:49.476(-4)? (STDERR)     at formatError (internal/util/inspect.js:915:13)
W20200626-22:41:49.477(-4)? (STDERR)     at formatRaw (internal/util/inspect.js:703:14)
W20200626-22:41:49.477(-4)? (STDERR)     at formatValue (internal/util/inspect.js:591:10)
W20200626-22:41:49.482(-4)? (STDERR)     at inspect (internal/util/inspect.js:221:10)
W20200626-22:41:49.482(-4)? (STDERR)     at formatWithOptions (internal/util/inspect.js:1693:40)
W20200626-22:41:49.483(-4)? (STDERR)     at Object.Console.<computed> (internal/console/constructor.js:272:10)
W20200626-22:41:49.483(-4)? (STDERR)     at Object.log (internal/console/constructor.js:282:61)
W20200626-22:41:49.483(-4)? (STDERR)     at Object.Meteor._debug (packages\meteor.js:1055:23)
W20200626-22:41:49.484(-4)? (STDERR)     at wrapInternalException (packages/ddp-server/livedata_server.js:1741:12)
W20200626-22:41:49.484(-4)? (STDERR)     at packages/ddp-server/livedata_server.js:745:25
W20200626-22:41:49.484(-4)? (STDERR)     at C:\Users\xxxxxx\AppData\Local\.meteor\packages\promise\0.11.2\npm\node_modules\meteor-promise\fiber_pool.js:43:40
I20200626-22:41:49.484(-4)? Sending error to Elastic APM { id: '74a6c5a216950b4a1b3f85f1b141628e' }
```

The client never gets the method callback. This was captured by the APM agent:

```
{"stack":{"stack":"TypeError: Cannot read property 'email' of undefined\n at MethodInvocation.finishEnrollment (server/methods.js:391:52)\n at MethodInvocation.<anonymous> (packages/kschingiz:meteor-elastic-apm/instrumenting/methods.js:36:42)\n at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1771:12)\n at packages/ddp-server/livedata_server.js:719:19\n at Meteor.EnvironmentVariable.EVp.withValue (packages\\meteor.js:1234:12)\n at packages/ddp-server/livedata_server.js:717:46\n at Meteor.EnvironmentVariable.EVp.withValue (packages\\meteor.js:1234:12)\n at packages/ddp-server/livedata_server.js:715:46\n at new Promise (<anonymous>)\n at Session.method (packages/ddp-server/livedata_server.js:689:23)\n at Session.<anonymous> (packages/kschingiz:meteor-elastic-apm/instrumenting/session.js:47:25)\n at packages/ddp-server/livedata_server.js:559:43","source":"method"},"message":"Cannot read property 'email' of undefined"}
```

I am currently running Meteor 1.9. With the following package versions as Meteor auto added them:
```
kschingiz:meteor-elastic-apm  added, version 2.4.0
kschingiz:meteor-measured     added, version 1.0.3
mongo-livedata                added, version 1.0.12
```

Any help on this would be greatly appreciated!

**Comment by kschingiz** [comment]
@Zjcompt Hi, I've checked the apm code, seems the problem is occurred on your method function code, could you please provide some simplified function code to understand why this happened? Better some small meteor project with the steps to reproduce.
Thanks!

**Comment by StorytellerCZ** [comment]
I'm closing this issues since we haven't heard back from @Zjcompt , feel free to re-open this issue with a reproduction.
